### PR TITLE
Koatlyn

### PR DESCRIPTION
**Pull request by Redrield**
fixed the robot code. im making 4069 great again

### CODE REVIEW

**Comment by solomondg** [comment]
i'm literally the best programmer in the world cause I use kotlin and I approve this message

**Comment by bfmat** [comment]
@solomondg @Redrield Kotlen r dum

**Comment by asinghani** [comment]
Kotlin is better than Swift. I vote to reopen

**Comment by asinghani** [comment]
@brendon-ai Kotlin is the superior programming language, so you should really reopen this

**Comment by Nomadluap** [comment]
​

**Comment by bfmat** [comment]
Why even is this a thing

**Pull request closed without merging**
